version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile     
    container_name: docker-django-vue-backend  
    volumes:
      - .:/app
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"


  vue:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: docker-django-vue-frontend
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - django