version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile     
    volumes:
      - .:/app
      - .db_data/db.sqlite3:/db.sqlite3


  vue:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - django