name: build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Thing
        run: |
          pwd;
          ls -allah

  notify-watchtower:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Notify Watchtower
        run: |
          curl -sL -v \
            --header 'Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}' \
            "${{ vars.WATCHTOWER_URL }}/v1/update"
